"""init

Revision ID: 00f0df917273
Revises: 8955338ec5b6
Create Date: 2023-11-15 23:32:08.488242

"""

# revision identifiers, used by Alembic.
revision = '00f0df917273'
down_revision = '8955338ec5b6'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
