"""init

Revision ID: 10889e2c0547
Revises: 8a9200490eab
Create Date: 2023-11-15 20:27:23.141053

"""

# revision identifiers, used by Alembic.
revision = '10889e2c0547'
down_revision = '8a9200490eab'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
