"""init

Revision ID: 699b477080ab
Revises: 97c20f7a5867
Create Date: 2023-11-16 00:17:08.628742

"""

# revision identifiers, used by Alembic.
revision = '699b477080ab'
down_revision = '97c20f7a5867'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
