"""init

Revision ID: 6a7bed476a24
Revises: 6bd28feb5c03
Create Date: 2023-11-15 21:27:23.131564

"""

# revision identifiers, used by Alembic.
revision = '6a7bed476a24'
down_revision = '6bd28feb5c03'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
