"""init

Revision ID: 6bd28feb5c03
Revises: 10889e2c0547
Create Date: 2023-11-15 21:12:23.190210

"""

# revision identifiers, used by Alembic.
revision = '6bd28feb5c03'
down_revision = '10889e2c0547'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
