"""init

Revision ID: 8955338ec5b6
Revises: ab0e7c430f3a
Create Date: 2023-11-15 23:17:08.508309

"""

# revision identifiers, used by Alembic.
revision = '8955338ec5b6'
down_revision = 'ab0e7c430f3a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
