"""init

Revision ID: 8a9200490eab
Revises: dd33cb03d01f
Create Date: 2023-11-15 19:27:23.114792

"""

# revision identifiers, used by Alembic.
revision = '8a9200490eab'
down_revision = 'dd33cb03d01f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('maximum_speed', sa.Integer(), nullable=False),
    sa.Column('in_stock', sa.Integer(), nullable=False),
    sa.Column('passenger_capacity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('order_details', 'product_id',
               existing_type=sa.VARCHAR(),
               type_=sa.String(),
               existing_nullable=False)
    op.create_foreign_key(None, 'order_details', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_details', type_='foreignkey')
    op.alter_column('order_details', 'product_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_table('products')
    # ### end Alembic commands ###
