"""init

Revision ID: 97c20f7a5867
Revises: c8f6fe26faf2
Create Date: 2023-11-16 00:02:08.578365

"""

# revision identifiers, used by Alembic.
revision = '97c20f7a5867'
down_revision = 'c8f6fe26faf2'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
