"""init

Revision ID: ab0e7c430f3a
Revises: eaa2692db750
Create Date: 2023-11-15 23:02:08.460252

"""

# revision identifiers, used by Alembic.
revision = 'ab0e7c430f3a'
down_revision = 'eaa2692db750'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
