"""init

Revision ID: c063356b47d1
Revises: 6a7bed476a24
Create Date: 2023-11-15 21:42:23.187951

"""

# revision identifiers, used by Alembic.
revision = 'c063356b47d1'
down_revision = '6a7bed476a24'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
