"""init

Revision ID: c8f6fe26faf2
Revises: 00f0df917273
Create Date: 2023-11-15 23:47:08.623723

"""

# revision identifiers, used by Alembic.
revision = 'c8f6fe26faf2'
down_revision = '00f0df917273'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
