"""init

Revision ID: eaa2692db750
Revises: c063356b47d1
Create Date: 2023-11-15 22:49:08.025521

"""

# revision identifiers, used by Alembic.
revision = 'eaa2692db750'
down_revision = 'c063356b47d1'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
